name: clear_weather
description: "Clean, minimal weather app with hourly forecasts and location-based updates."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  flutter_riverpod: ^3.0.0-dev.17
  intl: ^0.20.2
  geolocator: ^14.0.2
  lucide_icons_flutter: ^3.0.9
  shared_preferences: ^2.1.0
  open_meteo: ^2.1.6
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.0-dev.17
flutter:
  uses-material-design: true
